// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKgVLRmfdX039Zy30sed9pqXRZjR-lggk',
    appId: '1:994796054987:web:ca772b3922dcab006c2e4e',
    messagingSenderId: '994796054987',
    projectId: 'etamilnews-ddf8a',
    authDomain: 'etamilnews-ddf8a.firebaseapp.com',
    storageBucket: 'etamilnews-ddf8a.appspot.com',
    measurementId: 'G-YPBZYJNSV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpVZkX9ERCyb8oeSF4NuoijF52q0se4Hg',
    appId: '1:994796054987:android:9ca0a4fd669f750d6c2e4e',
    messagingSenderId: '994796054987',
    projectId: 'etamilnews-ddf8a',
    storageBucket: 'etamilnews-ddf8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiJpdwl-ZcAK-cnum51ZIt2atEWXF4qEI',
    appId: '1:994796054987:ios:8c770edc42230f0e6c2e4e',
    messagingSenderId: '994796054987',
    projectId: 'etamilnews-ddf8a',
    storageBucket: 'etamilnews-ddf8a.appspot.com',
    iosClientId: '994796054987-ogaitc96rp76k4274a3p3p4osdh3krms.apps.googleusercontent.com',
    iosBundleId: 'com.example.eTamilnews',
  );
}
